#!/bin/bash


echo 'Finding Hits'

./fh

echo 'Finding Members'

./fm

echo 'Finding Farmers'

./ff

echo 'Finding Alliances hitting us'

node findHits incoming

sleep 60

echo 'Fiding Enemies'

./fe

node generateIndex
node generateFolderIndex ally
node generateFolderIndex enemy
