#!/bin/bash

logfile=/home/ec2-user/trap4004/log/reports.log
exec > $logfile 2>&1

echo 'Finding Hits'

./fh

echo 'Finding Members'

./fm

echo 'Finding Farmers'

./ff

echo 'Finding Alliances hitting us'

node findHits incoming

sleep 60

echo 'Fiding Enemies'

./fe

node generateIndex
node generateFolderIndex ally
node generateFolderIndex enemy

node imgMembers
node imgMembers reports/farmers.txt reports/farmers.gif '-'
