#!/bin/bash

process=$(ps -o "%p %a" | grep 'node trap2' | grep -v grep | cut -d ' ' -f 1)


if [ ! -z $process ]
then
  kill $process
fi

cd /home/ec2-user/trap4004

nohup node trap2 2>&1 >> trap2.log&
